### ISSUE TITLE
Automated regression testing

### ISSUE THREAD

**Issue by apocalyptech** [apocalyptech/eschalon_utils#27]
I mentioned this in another issue, but figured it makes sense to fork it off.  It'd be nice to have some automated tests to make sure that changes haven't surreptitiously broken some existing data functionality.  I don't know how that could be accomplished on the GUI side (and it's probably not worth implementing there), but I imagine that with a set of maps and character files (from all three books), we could at least make sure that the data backend is loading/writing properly.

Not something I actually care enough about to implement at the moment; we'll see if this ever gets done.  It's something which probably would have been more useful over the past few months, as Book III support's been solidified.

**Comment by grimreaper** [comment]
This was resolved in 365755424c3460ee35d0b19d2b425675056e3cc3 and f220941982f5430acab3359525af14732529b368

We can do more, but likely under the guise of a future ticket (or test coverage)
