### ISSUE TITLE
Launcher does not stay open.

### ISSUE THREAD

**Issue by raverdave2k** [apocalyptech/eschalon_utils#42]
I've only just realised there was a launcher included with the editors and as of now I'll be using it as my starting point.

The only negative (an this is purely personal preference rather than an issue) is that it closes once you open one of the editors rather than staying open.

I've managed to stop this happening by removing the following two lines from under the Character Button and Map Button sections of eschalon_utils.py (Lines 67 & 69 and 78 & 80)

```
#button.connect_object("clicked", gtk.Widget.hide, self.window)
#button.connect_object("clicked", gtk.Widget.destroy, self.window)
```

Obviously other people might have a different opinion and prefer it close so I don't really know if it's something that should be changed, unless perhaps you can add a tick box to the window to toggle this behaviour on and off?

**Comment by grimreaper** [comment]
I've changed the way the launcher works and will not likely implement stay-open behavior. Instead something closer to a menu bar "select book" is more likely to be used.
