### ISSUE TITLE
Warning to the user when using char editor and pycrypto's not installed, on Books 2 and 3?

### ISSUE THREAD

**Issue by apocalyptech** [apocalyptech/eschalon_utils#59]
Should probably display a note to the user if they run the character editor and pycrypto's not installed, similar to what we do with czipfile on the map editor.  Pycrypto's not necessary, of course, but it does make item editing nicer.

If implemented, that dialog should also have a "show this dialog in the future?" checkbox like the czipfile dialog.

**Comment by grimreaper** [comment]
I'm moving in a direction on requiring all dependencies. Having multiple flows for graceful degradation is difficult to test and not required for a minor application like this.

For a more complex library this kind of work might make sense.
